### ISSUE TITLE
How to create a Tube shape

### ISSUE THREAD

**Issue by Gergling** [nosir/obelisk.js#17]
I want to create a tube-shape. How would you recommend going about this?

**Comment by nosir** [comment]
Hi, Gergling, to assemble the tube-shape, i guess the only way for now is to put 4 cuboid together, something like this: 
![tube](https://cloud.githubusercontent.com/assets/352617/5593451/a9919ad0-9263-11e4-93c2-249cfa0999b4.gif)

**Comment by Gergling** [comment]
What if I wanted to create a tube with more sides, such as a circular or octagonal prism? Is that possible?

**Comment by nosir** [comment]
This seems not possible atm :p

**Comment by Gergling** [comment]
Ok thanks.
