### ISSUE TITLE
Scale Problem ?

### ISSUE THREAD

**Issue by Nik0w** [nosir/obelisk.js#21]
Hi, when i set my canvas to width and height 100%, all of isometrics objects apears very fat and pixelised ... I don't understand .. (sorry for my english)

**Comment by nosir** [comment]
The way you did will change the aspect ratio of the canvas, what you really want is to dynamically adjust canvas size to viewport size, so in javascript: 
```
function resize() {
	canvas.width = window.innerWidth;
	canvas.height = window.innerHeight;

	// other render logic
}

window.addEventListener('resize', resize);
resize();
```

**Comment by Nik0w** [comment]
Hi,

Thanks, but the prob seems to be caused by the canvas context size and not the canvas size directly ^^..

It's ok now :) !

**Comment by nosir** [comment]
Glad you solved that :+1:
