### ISSUE TITLE
Release v1.2.2 on GitHub

### ISSUE THREAD

**Issue by extend1994** [nosir/obelisk.js#26]
Hi I am member from cdnjs and is going to add obelisk.js to cdnjs.
cdnjs will automatically fetch releases on GitHub or npm and then add them to CDN.
So it would be great to have v1.2.2 on GitHub!
Is it possible for you to do that?
Thanks!

**Comment by nosir** [comment]
Hi @extend1994 v1.2.2 released.
It was published in npm.
Thanks!

**Comment by extend1994** [comment]
@nosir Thanks! I will cc you as soon as I open the pull request to add this library 😃
